'use client'

import React from 'react'
import { Card } from '@/components/ui/Card'

interface ClaimSummaryProps {
  forSummary: string
  againstSummary: string
}

export const ClaimSummary: React.FC<ClaimSummaryProps> = ({ forSummary, againstSummary }) => {
  return (
    <div className="grid grid-cols-1 md:grid-cols-2 gap-4 sm:gap-6 mb-6 sm:mb-8 pt-10">
      {/* For Summary */}
      <Card className="p-4 sm:p-6 bg-[#E9F2FF] border-[#1066DE] rounded-2xl sm:rounded-3xl">
        <h3 className="text-base sm:text-lg lg:text-xl font-semibold text-gray-900 mb-2">
          Leading Position Summary (For)
        </h3>
        <p className="text-gray-700 leading-relaxed text-xs sm:text-sm">"{forSummary}"</p>
      </Card>

      {/* Against Summary (Steel Man) */}
      <Card className="p-4 sm:p-6 bg-[#FFF5DE] border-[#A68333] rounded-2xl sm:rounded-3xl">
        <h3 className="text-base sm:text-lg lg:text-xl font-semibold text-[#A68333] mb-2">
          Steel Man of Opposing View (Against)
        </h3>
        <p className="text-xs text-[#A68333] mb-3 italic">
          A fair, thoughtful restatement of the best opposing argument, generated by AI to promote
          deeper understanding
        </p>
        <p className="text-gray-700 leading-relaxed text-xs sm:text-sm">"{againstSummary}"</p>
      </Card>
    </div>
  )
}

