'use client'

import React, { useMemo } from 'react'
import { Card } from '@/components/ui/Card'
import { Evidence } from '@/lib/types'

interface ClaimSummaryProps {
  evidence: Evidence[]
}

export const ClaimSummary: React.FC<ClaimSummaryProps> = ({ evidence = [] }) => {
  const { forSummary, againstSummary } = useMemo(() => {
    if (!evidence || evidence.length === 0) {
      return { forSummary: '', againstSummary: '' }
    }
    
    const forEvidence = evidence
      .filter((e) => e.position === 'for' && e.aiSummary && e.aiSummary.trim().length > 0)
      .sort((a, b) => (b.upvotes || 0) - (a.upvotes || 0))
    
    const againstEvidence = evidence
      .filter((e) => e.position === 'against' && e.aiSummary && e.aiSummary.trim().length > 0)
      .sort((a, b) => (b.upvotes || 0) - (a.upvotes || 0))
    
    return {
      forSummary: forEvidence[0]?.aiSummary || '',
      againstSummary: againstEvidence[0]?.aiSummary || '',
    }
  }, [evidence])

  return (
    <div className="grid grid-cols-1 md:grid-cols-2 gap-4 sm:gap-6 mb-6 sm:mb-8 pt-5">
      {/* For Summary */}
      <Card className="p-4 sm:p-6 bg-[#E9F2FF] dark:bg-blue-900/20 border-[#1066DE] dark:border-blue-500 rounded-2xl sm:rounded-3xl">
        <h3 className="text-base sm:text-lg lg:text-xl font-semibold text-gray-900 dark:text-gray-100 mb-2">
          Leading Position Summary (For)
        </h3>
        {forSummary ? (
          <p className="text-gray-700 dark:text-gray-300 leading-relaxed text-xs sm:text-sm">"{forSummary}"</p>
        ) : (
          <p className="text-gray-500 dark:text-gray-400 italic text-xs sm:text-sm">No summary available</p>
        )}
      </Card>

      {/* Against Summary (Steel Man) */}
      <Card className="p-4 sm:p-6 bg-[#FFF5DE] dark:bg-yellow-900/20 border-[#A68333] dark:border-yellow-600 rounded-2xl sm:rounded-3xl">
        <h3 className="text-base sm:text-lg lg:text-xl font-semibold text-[#A68333] dark:text-yellow-400 mb-2">
          Steel Man of Opposing View (Against)
        </h3>
        <p className="text-xs text-[#A68333] dark:text-yellow-400 mb-3 italic">
          A fair, thoughtful restatement of the best opposing argument, generated by AI to promote
          deeper understanding
        </p>
        {againstSummary ? (
          <p className="text-gray-700 dark:text-gray-300 leading-relaxed text-xs sm:text-sm">"{againstSummary}"</p>
        ) : (
          <p className="text-gray-500 dark:text-gray-400 italic text-xs sm:text-sm">No summary available</p>
        )}
      </Card>
    </div>
  )
}

